### ISSUE TITLE
出现错误 QQ版本过低

### ISSUE THREAD

**Issue by Hibari233** [hundunzhidian/valvemiraibot#4]
`
net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo=)
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:238) ~[mirai-core-jvm-2.6-M1.jar!/:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt) ~[mirai-core-jvm-2.6-M1.jar!/:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.4.32.jar!/:1.4.32-release-371 (1.4.32)]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.4.32.jar!/:1.4.32-release-371 (1.4.32)]
	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:250) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:123) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:308) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:318) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1411) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:853) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:803) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:90) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$PacketListener.complete(QQAndroidBotNetworkHandler.kt) ~[mirai-core-jvm-2.6-M1.jar!/:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.handlePacket(QQAndroidBotNetworkHandler.kt:533) ~[mirai-core-jvm-2.6-M1.jar!/:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:504) ~[mirai-core-jvm-2.6-M1.jar!/:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt) ~[mirai-core-jvm-2.6-M1.jar!/:na]
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseOicqResponse(PacketFactory.kt:439) ~[mirai-core-jvm-2.6-M1.jar!/:na]
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:294) ~[mirai-core-jvm-2.6-M1.jar!/:na]
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:246) ~[mirai-core-jvm-2.6-M1.jar!/:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:495) ~[mirai-core-jvm-2.6-M1.jar!/:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:490) ~[mirai-core-jvm-2.6-M1.jar!/:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:472) ~[mirai-core-jvm-2.6-M1.jar!/:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.4.32.jar!/:1.4.32-release-371 (1.4.32)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[kotlinx-coroutines-core-1.3.6.jar!/:na]

`

**Comment by hundunzhidian** [comment]
腾讯对于机器人的风险管控，建议使用大号登录几次，device文件是随机生成的设备文件，非必要不要删除
